import type { SheetMenuItem } from "./get-menu"

export const fallbackMenu: SheetMenuItem[] = [
  {
    categoria: "Entrada",
    titulo_seccion: "Para empezar",
    descripcion_seccion: "Pequeños bocados para abrir el apetito.",
    orden: 1,
    platillo: "Escabeche de chivo con pan casero",
    descripcion: "",
    precio: 3500,
    disponible: true,
    tags: ["Regional"],
    especial: false,
  },
  {
    categoria: "Platos Principales",
    titulo_seccion: "Del fuego",
    descripcion_seccion: "Especialidades preparadas al momento.",
    orden: 2,
    platillo: "Chivo del norte Neuquino",
    descripcion: "Cocción al horno. Consultar con anticipación.",
    precio: 34000,
    disponible: true,
    tags: ["Regional"],
    especial: true,
  },
  {
    categoria: "Postres",
    titulo_seccion: "Dulce final",
    descripcion_seccion: "El cierre perfecto para una comida memorable.",
    orden: 3,
    platillo: "Flan casero",
    descripcion: "Con dulce de leche y/o crema chantilly",
    precio: 9000,
    disponible: true,
    tags: [],
    especial: false,
  },
  {
    categoria: "Bebidas",
    titulo_seccion: "Para acompañar",
    descripcion_seccion: "Jugos, cervezas y vinos neuquinos.",
    orden: 4,
    platillo: "Jugo natural",
    descripcion: "Fruta fresca del día",
    precio: 8000,
    disponible: true,
    tags: [],
    especial: false,
  },
]
